# Generated by Django 4.1.10 on 2023-08-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created']},
        ),
    ]
