# Generated by Django 4.1.10 on 2023-08-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
    ]
